/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.EmpresaDAO;
import Controller.PropriedadeDAO;
import Controller.UsuarioDAO;
import Model.Empresa;
import Model.Propriedade;
import Model.Usuario;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class FormOpcoes extends javax.swing.JInternalFrame {

    int id, op;
    double vt;
    PLCRLobby pp;
    Empresa atu;
    /**
     * Creates new form FormOpcoes
     */
    public FormOpcoes() {
        initComponents();
        ConfigurarForm(0);
    }

    public FormOpcoes(int i, PLCRLobby back) {
        initComponents();
        ConfigurarForm(i);
        pp = back;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeral = new javax.swing.JPanel();
        lblNomeAcao = new javax.swing.JLabel();
        tbdMercadoNegociar = new javax.swing.JTabbedPane();
        pnlMercado = new javax.swing.JPanel();
        lblValorAtual = new javax.swing.JLabel();
        tglTipo = new javax.swing.JToggleButton();
        pnlInfo = new javax.swing.JPanel();
        pnlQuantidade = new javax.swing.JPanel();
        lblQuantidade = new javax.swing.JLabel();
        spnQuantidade = new javax.swing.JSpinner();
        pnlValorTotal = new javax.swing.JPanel();
        lblValorTotal = new javax.swing.JLabel();
        lblValorTotalNum = new javax.swing.JLabel();
        pnlSenha = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        pnlFinalizar = new javax.swing.JPanel();
        lblFinalizar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        pnlGeral.setBackground(new java.awt.Color(255, 255, 255));
        pnlGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2));

        lblNomeAcao.setFont(new java.awt.Font("Game Of Squids", 0, 36)); // NOI18N
        lblNomeAcao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeAcao.setText("NOME");

        tbdMercadoNegociar.setBackground(new java.awt.Color(255, 255, 255));
        tbdMercadoNegociar.setToolTipText("");
        tbdMercadoNegociar.setFont(new java.awt.Font("Game Of Squids", 0, 12)); // NOI18N
        tbdMercadoNegociar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdMercadoNegociarMouseClicked(evt);
            }
        });

        pnlMercado.setBackground(new java.awt.Color(255, 255, 255));
        pnlMercado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2));

        lblValorAtual.setFont(new java.awt.Font("Game Of Squids", 0, 18)); // NOI18N
        lblValorAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorAtual.setText("VALOR POR UNIDADE:");

        tglTipo.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        tglTipo.setText("TIPO");
        tglTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglTipoActionPerformed(evt);
            }
        });

        pnlInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        pnlQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblQuantidade.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        lblQuantidade.setText("QUANTIDADE");

        spnQuantidade.setFont(new java.awt.Font("Game Of Squids", 0, 12)); // NOI18N
        spnQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spnQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantidadeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlQuantidadeLayout = new javax.swing.GroupLayout(pnlQuantidade);
        pnlQuantidade.setLayout(pnlQuantidadeLayout);
        pnlQuantidadeLayout.setHorizontalGroup(
            pnlQuantidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuantidadeLayout.createSequentialGroup()
                .addGroup(pnlQuantidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuantidadeLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlQuantidadeLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblQuantidade)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnlQuantidadeLayout.setVerticalGroup(
            pnlQuantidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuantidadeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlValorTotal.setBackground(new java.awt.Color(255, 255, 255));
        pnlValorTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblValorTotal.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        lblValorTotal.setText("VALOR TOTAL");

        lblValorTotalNum.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        lblValorTotalNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorTotalNum.setText("R$: 0");

        javax.swing.GroupLayout pnlValorTotalLayout = new javax.swing.GroupLayout(pnlValorTotal);
        pnlValorTotal.setLayout(pnlValorTotalLayout);
        pnlValorTotalLayout.setHorizontalGroup(
            pnlValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValorTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValorTotal)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorTotalNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlValorTotalLayout.setVerticalGroup(
            pnlValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValorTotalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblValorTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValorTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSenha.setBackground(new java.awt.Color(255, 255, 255));
        pnlSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SUA SENHA");

        javax.swing.GroupLayout pnlSenhaLayout = new javax.swing.GroupLayout(pnlSenha);
        pnlSenha.setLayout(pnlSenhaLayout);
        pnlSenhaLayout.setHorizontalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSenha)
                .addContainerGap())
        );
        pnlSenhaLayout.setVerticalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        pnlFinalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2));
        pnlFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        pnlFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlFinalizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlFinalizarMouseExited(evt);
            }
        });

        lblFinalizar.setFont(new java.awt.Font("Game Of Squids", 0, 24)); // NOI18N
        lblFinalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalizar.setText("FINALIZAR");
        lblFinalizar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFinalizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblFinalizarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlFinalizarLayout = new javax.swing.GroupLayout(pnlFinalizar);
        pnlFinalizar.setLayout(pnlFinalizarLayout);
        pnlFinalizarLayout.setHorizontalGroup(
            pnlFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinalizarLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lblFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        pnlFinalizarLayout.setVerticalGroup(
            pnlFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addComponent(pnlFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pnlMercadoLayout = new javax.swing.GroupLayout(pnlMercado);
        pnlMercado.setLayout(pnlMercadoLayout);
        pnlMercadoLayout.setHorizontalGroup(
            pnlMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMercadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValorAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlMercadoLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(tglTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMercadoLayout.setVerticalGroup(
            pnlMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMercadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdMercadoNegociar.addTab("MERCADO", pnlMercado);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbdMercadoNegociar.addTab("NEGOCIAR", jPanel3);

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdMercadoNegociar)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(lblNomeAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblNomeAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbdMercadoNegociar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantidadeStateChanged
        int quant;
        quant = Integer.parseInt(spnQuantidade.getValue().toString());
        if(quant>0)
        {
            double valor;
            valor = quant * atu.getValor();
            vt = valor;
            lblValorTotalNum.setText("R$: " + valor);
        }
        else if(quant==0)
        {
            lblValorTotalNum.setText("R$:");
        }
    }//GEN-LAST:event_spnQuantidadeStateChanged

    private void tbdMercadoNegociarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdMercadoNegociarMouseClicked
            Empresa emp;
            emp = new EmpresaDAO().encontrarId(id);
            lblNomeAcao.setText(emp.getNome());
            lblValorAtual.setText("VALOR POR UNIDADE: R$" + emp.getValor());
            atu = emp;
    }//GEN-LAST:event_tbdMercadoNegociarMouseClicked

    private void tglTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglTipoActionPerformed
        if(op==0)
        {
            op=1;
            tglTipo.setText("VENDER");
            Operacao(1);
        }
        else
        {
            op=0;
            tglTipo.setText("COMPRAR");
            Operacao(0);
        }
    }//GEN-LAST:event_tglTipoActionPerformed

    private void pnlFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFinalizarMouseEntered
       mouse(0);
    }//GEN-LAST:event_pnlFinalizarMouseEntered

    private void pnlFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFinalizarMouseExited
        mouse(1);
    }//GEN-LAST:event_pnlFinalizarMouseExited

    private void pnlFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFinalizarMouseClicked
        confirm();
    }//GEN-LAST:event_pnlFinalizarMouseClicked

    private void lblFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizarMouseClicked
        confirm();
    }//GEN-LAST:event_lblFinalizarMouseClicked

    private void lblFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizarMouseEntered
        mouse(0);
    }//GEN-LAST:event_lblFinalizarMouseEntered

    private void lblFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFinalizarMouseExited
        mouse(1);
    }//GEN-LAST:event_lblFinalizarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblFinalizar;
    private javax.swing.JLabel lblNomeAcao;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValorAtual;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorTotalNum;
    private javax.swing.JPanel pnlFinalizar;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlMercado;
    private javax.swing.JPanel pnlQuantidade;
    private javax.swing.JPanel pnlSenha;
    private javax.swing.JPanel pnlValorTotal;
    private javax.swing.JSpinner spnQuantidade;
    private javax.swing.JTabbedPane tbdMercadoNegociar;
    private javax.swing.JToggleButton tglTipo;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables


    private void ConfigurarForm(int tip)
    {
        this.setTitle("Ações");
        this.setResizable(false);
        tglTipo.setSelected(false);
        Operacao(0);
        op=0;
        if(tip>0)
        {
            Empresa emp;
            emp = new EmpresaDAO().encontrarId(tip);
            lblNomeAcao.setText(emp.getNome());
            lblValorAtual.setText("VALOR POR UNIDADE: R$" + emp.getValor());
            atu = emp;
            id = tip;
        }
        
    }
 
    private void Operacao(int i)
    {
        if(i==0)
        {
             tglTipo.setText("COMPRAR");
             tglTipo.setForeground(Color.GREEN);
             lblValorTotal.setForeground(Color.GREEN);
             lblValorTotalNum.setForeground(Color.GREEN);
             lblFinalizar.setForeground(Color.GREEN);
        }
        else
        {
            tglTipo.setText("VENDER");
            tglTipo.setForeground(Color.RED);
            lblValorTotal.setForeground(Color.RED);
            lblValorTotalNum.setForeground(Color.RED);
            lblFinalizar.setForeground(Color.RED);
        }
    }
    
    private void mouse(int tipo)
    {
        if(op==0)
        {
          if(tipo==0)
            {

                pnlFinalizar.setBackground(Color.GREEN);
                lblFinalizar.setForeground(Color.WHITE);

            }
            else
            {
                pnlFinalizar.setBackground(Color.WHITE);
                lblFinalizar.setForeground(Color.GREEN);
            }  
        }
        else
        {
            if(tipo==0)
            {

                pnlFinalizar.setBackground(Color.RED);
                lblFinalizar.setForeground(Color.WHITE);

            }
            else
            {
                pnlFinalizar.setBackground(Color.WHITE);
                lblFinalizar.setForeground(Color.RED);
            }
        }
        
    }

    
    public void confirm()
    {
        if(txtSenha.getPassword().length<10)
        {
            JOptionPane.showMessageDialog(
                    null,
                    "A senha deve ter no minimo 10 caracteres",
                    "Operação",
                    JOptionPane.ERROR_MESSAGE
                );
            
        }
        else
        {
            if (new UsuarioDAO().login(pp.getDoc(), new String(txtSenha.getPassword()))){
                
                //login realizado com sucesso!
                Usuario us = new UsuarioDAO().pesquisarCpfSenha(pp.getDoc(), new String(txtSenha.getPassword()));
                
                if(us.getSaldo() < Integer.parseInt(spnQuantidade.getValue().toString()) && op==0)
                {
                    JOptionPane.showMessageDialog(
                            null,
                            "SALDO INSUFICIENTE",
                            "SALDO",
                            JOptionPane.ERROR_MESSAGE
                        );
                }
                else
                {
                    Propriedade pro = new Propriedade();
                    pro.setId_empresa(id);
                    pro.setCpf_user(pp.getDoc());
                    pro.setQuantidade(Integer.parseInt(spnQuantidade.getValue().toString()));
                    pro.setValor_uni(atu.getValor());
                    PropriedadeDAO prodao = new PropriedadeDAO();
                    int resul = prodao.veri(pro, op);
                    if(resul>=1)
                    {
                        if(op==0)
                        {
                            us.setSaldo(us.getSaldo()-(atu.getValor()* Integer.parseInt(spnQuantidade.getValue().toString())));
                            JOptionPane.showMessageDialog(
                                null,
                                "COMPRA EFETIVADA!.",
                                "PLCR",
                                JOptionPane.INFORMATION_MESSAGE
                            );
                           
                        }
                        else
                        {
                            us.setSaldo(us.getSaldo()+(atu.getValor()* Integer.parseInt(spnQuantidade.getValue().toString())));
                            JOptionPane.showMessageDialog(
                                null,
                                "VENDA EFETIVADA!.",
                                "PLCR",
                                JOptionPane.INFORMATION_MESSAGE
                            );
                        }
                        new UsuarioDAO().atualizar(us);
                        pp.atualizar( new String(txtSenha.getPassword()));
                        this.dispose();
                    }
                    else
                    {
                        if(resul == -1)
                        {
                            JOptionPane.showMessageDialog(
                                null,
                                "Ocorreu um erro.",
                                "PLCR",
                                JOptionPane.ERROR_MESSAGE
                            );
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(
                                null,
                                "VOCÊ NÃO POSSUI ESSA QUANTIDAE DE AÇÕES",
                                "PLCR",
                                JOptionPane.ERROR_MESSAGE
                            );
                        }
                    }
                }
                
                
            }
        }
    }
}
