/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author Pedro
 */
public class FormOpcoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormOpcoes
     */
    public FormOpcoes() {
        initComponents();
        ConfigurarForm();
    }

    FormOpcoes(int i) {
        initComponents();
        ConfigurarForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeral = new javax.swing.JPanel();
        lblNomeAcao = new javax.swing.JLabel();
        tbdMercadoNegociar = new javax.swing.JTabbedPane();
        pnlMercado = new javax.swing.JPanel();
        lblValorAtual = new javax.swing.JLabel();
        tglTipo = new javax.swing.JToggleButton();
        pnlInfo = new javax.swing.JPanel();
        pnlQuantidade = new javax.swing.JPanel();
        lblQuantidade = new javax.swing.JLabel();
        spnQuantidade = new javax.swing.JSpinner();
        pnlValorTotal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblValorTotalNum = new javax.swing.JLabel();
        pnlSenha = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        pnlFinalizar = new javax.swing.JPanel();
        lblFinalizar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        pnlGeral.setBackground(new java.awt.Color(255, 255, 255));
        pnlGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2));

        lblNomeAcao.setFont(new java.awt.Font("Game Of Squids", 0, 24)); // NOI18N
        lblNomeAcao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeAcao.setText("NOME");

        tbdMercadoNegociar.setBackground(new java.awt.Color(255, 255, 255));
        tbdMercadoNegociar.setToolTipText("");
        tbdMercadoNegociar.setFont(new java.awt.Font("Game Of Squids", 0, 12)); // NOI18N

        pnlMercado.setBackground(new java.awt.Color(255, 255, 255));
        pnlMercado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2));

        lblValorAtual.setFont(new java.awt.Font("Game Of Squids", 0, 18)); // NOI18N
        lblValorAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorAtual.setText("VALOR ATUAL:");

        tglTipo.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        tglTipo.setText("TIPO");

        pnlInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlQuantidade.setBackground(new java.awt.Color(255, 255, 255));
        pnlQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblQuantidade.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        lblQuantidade.setText("QUANTIDADE");

        spnQuantidade.setFont(new java.awt.Font("Game Of Squids", 0, 12)); // NOI18N
        spnQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spnQuantidade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantidadeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlQuantidadeLayout = new javax.swing.GroupLayout(pnlQuantidade);
        pnlQuantidade.setLayout(pnlQuantidadeLayout);
        pnlQuantidadeLayout.setHorizontalGroup(
            pnlQuantidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuantidadeLayout.createSequentialGroup()
                .addGroup(pnlQuantidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlQuantidadeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuantidade))
                    .addGroup(pnlQuantidadeLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlQuantidadeLayout.setVerticalGroup(
            pnlQuantidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQuantidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlValorTotal.setBackground(new java.awt.Color(255, 255, 255));
        pnlValorTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        jLabel4.setText("VALOR TOTAL");

        lblValorTotalNum.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        lblValorTotalNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorTotalNum.setText("R$:");

        javax.swing.GroupLayout pnlValorTotalLayout = new javax.swing.GroupLayout(pnlValorTotal);
        pnlValorTotal.setLayout(pnlValorTotalLayout);
        pnlValorTotalLayout.setHorizontalGroup(
            pnlValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValorTotalLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblValorTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValorTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(88, 88, 88))
        );
        pnlValorTotalLayout.setVerticalGroup(
            pnlValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValorTotalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSenha.setBackground(new java.awt.Color(255, 255, 255));
        pnlSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Game Of Squids", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SUA SENHA");

        javax.swing.GroupLayout pnlSenhaLayout = new javax.swing.GroupLayout(pnlSenha);
        pnlSenha.setLayout(pnlSenhaLayout);
        pnlSenhaLayout.setHorizontalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSenhaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSenha)
                .addContainerGap())
        );
        pnlSenhaLayout.setVerticalGroup(
            pnlSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlFinalizar.setBackground(new java.awt.Color(255, 255, 255));
        pnlFinalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 2));
        pnlFinalizar.setForeground(new java.awt.Color(255, 255, 255));

        lblFinalizar.setFont(new java.awt.Font("Game Of Squids", 0, 24)); // NOI18N
        lblFinalizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFinalizar.setText("FINALIZAR");
        lblFinalizar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pnlFinalizarLayout = new javax.swing.GroupLayout(pnlFinalizar);
        pnlFinalizar.setLayout(pnlFinalizarLayout);
        pnlFinalizarLayout.setHorizontalGroup(
            pnlFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFinalizarLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lblFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        pnlFinalizarLayout.setVerticalGroup(
            pnlFinalizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFinalizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(pnlQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMercadoLayout = new javax.swing.GroupLayout(pnlMercado);
        pnlMercado.setLayout(pnlMercadoLayout);
        pnlMercadoLayout.setHorizontalGroup(
            pnlMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMercadoLayout.createSequentialGroup()
                .addGroup(pnlMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMercadoLayout.createSequentialGroup()
                        .addGroup(pnlMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMercadoLayout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(lblValorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMercadoLayout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(tglTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 260, Short.MAX_VALUE))
                    .addGroup(pnlMercadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMercadoLayout.setVerticalGroup(
            pnlMercadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMercadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdMercadoNegociar.addTab("MERCADO", pnlMercado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        tbdMercadoNegociar.addTab("NEGOCIAR", jPanel3);

        javax.swing.GroupLayout pnlGeralLayout = new javax.swing.GroupLayout(pnlGeral);
        pnlGeral.setLayout(pnlGeralLayout);
        pnlGeralLayout.setHorizontalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdMercadoNegociar)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(lblNomeAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGeralLayout.setVerticalGroup(
            pnlGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGeralLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblNomeAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbdMercadoNegociar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnQuantidadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantidadeStateChanged
        int quant;
        quant = Integer.parseInt(spnQuantidade.getValue().toString());
        if(quant>0)
        {
            lblValorTotalNum.setText("R$: 20,00");
        }
        else if(quant==0)
        {
            lblValorTotalNum.setText("R$:");
        }
    }//GEN-LAST:event_spnQuantidadeStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFinalizar;
    private javax.swing.JLabel lblNomeAcao;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValorAtual;
    private javax.swing.JLabel lblValorTotalNum;
    private javax.swing.JPanel pnlFinalizar;
    private javax.swing.JPanel pnlGeral;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlMercado;
    private javax.swing.JPanel pnlQuantidade;
    private javax.swing.JPanel pnlSenha;
    private javax.swing.JPanel pnlValorTotal;
    private javax.swing.JSpinner spnQuantidade;
    private javax.swing.JTabbedPane tbdMercadoNegociar;
    private javax.swing.JToggleButton tglTipo;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables


    private void ConfigurarForm()
    {
        this.setTitle("Ações");
        this.setResizable(false);
    }
 


}
